name: Automatically updating manifest file

on: 
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Running manifest generator script
        working-directory: "."
        continue-on-error: false
        run: |
          python3 -u manifest_gen.py
          
      - name: Committing manifest file changes
        working-directory: "."
        continue-on-error: false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git status
          git add manifest.json
          git commit -m "🤖 Automatically updated manifest.json file" -a
      
      - name: Push changes if any
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}